# Generated by Django 5.0 on 2023-12-07 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_notes_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, которому принадлежит заметка.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.telegramuser', verbose_name='Пользователь'),
        ),
    ]
