# Generated by Django 5.0 on 2023-12-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_notes_options_alter_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='page',
        ),
    ]
